# -*- coding: utf-8 -*-
"""DOc genie.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rQyG9GbytzDx8gmxUUt9_DsF3mANcet9
"""

pip install -U transformers

from transformers import pipeline

pipe=pipeline("text-generation",model="ibm-granite/granite-3.3-2b-instruct")
messages =[
    {"role":"user","content":"who are you?"},
]
pipe(messages)

from transformers import AutoTokenizer,AutoModelForCausalLM
tokenizer=AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model=AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages=[
    {"role":"user","content":"who are you?"},
]
inputs=tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)
outputs= model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0] [inputs["input_ids"].shape[-1]:]))

!pip install -q gradio transformers torch black autopep8 reportlab requests

!pip install -q gradio transformers torch black autopep8 reportlab requests

import gradio as gr
from datetime import datetime
from pathlib import Path
import json
import re
import ast
import requests
import urllib.parse
import inspect

from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    PageBreak, Table, TableStyle, Preformatted
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors

!pip install -q gradio transformers torch black autopep8 reportlab requests

import gradio as gr
from datetime import datetime
from pathlib import Path
import json
import re
import ast
import requests
import urllib.parse
import inspect

from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    PageBreak, Table, TableStyle, Preformatted
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors